### ISSUE TITLE
Add new mechanic

### ISSUE THREAD

**Issue by VuongVy** [alexzvn/oraxen#2]
- Harvest required Hoe Tools
- After harvest farmland change to dirt

**Comment by alexzvn** [comment]
@VuongVy what if player mean to break plants

**Comment by VuongVy** [comment]
Break: drop > plants disappear > farmland change to dirt @alexzvn

**Comment by alexzvn** [comment]
farmland change to dirt after harvest implemented at https://github.com/alexzvn/oraxen/tree/61e68ddaf091892f823574c08988816c50b325bb

**Comment by alexzvn** [comment]
@VuongVy `Harvest required Hoe Tools:` please describe more detail about some possible case. For example, what if they just click(harvest) to plants but don't have right tools.

**Comment by VuongVy** [comment]
@alexzvn notify to player "u dont have right tools" when player click but dont have right tools.

**Comment by alexzvn** [comment]
feature added
